server:
  port: 8082

spring:
  application:
    name: activity-service

  mongodb:
    uri: mongodb://localhost:27017/fitness_activity_db

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    activity-events: activity-events

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
